version: "3"
services:
    nginx:
        image: "nginx:latest"
        ports:
            - "8080:80"
        depends_on:
            - db
    web:
        build: .
        ports:
            - "8000:8080"
        depends_on:
            - db
    db:
        image: "microsoft/mssql-server-windows-developer"
        ports:
            - "11433:1433"
        environment:
            SA_PASSWORD: ${TFSDBPASS}
            ACCEPT_EULA: "Y"