version: "3"
services:
    tfs:
        image: "tfsbase:latest"
        ports:
            - "8080:80"
        depends_on:
            - db
    web:
        image: "microsoft/iis"
        ports:
            - "8000:80"
        depends_on:
            - db
    db:
        image: "microsoft/mssql-server-windows-developer"
        ports:
            - "11433:1433"
        environment:
            SA_PASSWORD: ${TFSDBPASS}
            ACCEPT_EULA: "Y"